openapi: "3.0.3"
info:
  title: Request for tasks
  version: 1.0.0
  description: OpenAPI Specification for tasks

servers:
  - url: /delphin

paths:
  /tasks/{taskId}:
    get:
      tags:
        - Task
      description: Получение задачи по id
      operationId: get-task-by-id
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор задачи
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: 'model/task_response.json'
        404:
          description: Not Found
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden