version: '3'

services:
  content-db:
    image: postgres:10.7
    ports:
    - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: content
      POSTGRES_USER: content
      POSTGRES_PASSWORD: content